COMMON_ALL_PLAYERS_MAP = {
    "DISPLAY_LAST_COMMA_FIRST": "full_name",
    "ROSTERSTATUS": "active",
    "FROM_YEAR": "from_year",
    "TO_YEAR": "to_year"
}
STATS_MAP = {
    "GP": "games_played",
    "GS": "games_started",
    "W": "wins",
    "L": "losses",
    "W_PCT": "win_percent",
    "MIN": "minutes",
    "FGM": "fgm",
    "FGA": "fga",
    "FG_PCT": "fg_pct",
    "FTM": "ftm",
    "FTA": "fta",
    "FT_PCT": "ft_pct",
    "FG3M": "fg3m",
    "FG3A": "fg3a",
    "FG3_PCT": "fg3_pct",
    "OREB": "offensive_rebounds",
    "DREB": "defensive_rebounds",
    "REB": "rebounds",
    "AST": "assists",
    "STL": "steals",
    "BLK": "blocks",
    "TOV": "turnovers",
    "PF": "fouls",
    "PTS": "points",
    "PLUS_MINUS": "plus_minus",
    "SEASON_ID": "season",
    "GROUP_VALUE": "tag",
    "PLAYER_AGE": "age",
}
